### ISSUE TITLE
Add a note about checking for CPU Compatibility for target-cpu=native

### ISSUE THREAD

**Issue by joshuataylor** [nnethercote/perf-book#43]
Hi, love the book, it's great!

With M1 Macs there is currently an issue where using `target-cpu=native` doesn't detect all the CPU features.

See this: https://github.com/rust-lang/rust/issues/93889

You need to pass `apple-m1` instead (though this should be fixed soon in an upcoming llvm release, though same thing would happen for other newer CPUs).

Maybe make a note about comparing `rustc --print cfg` and `rustc --print cfg -Ctarget-cpu=native` if the user is relying on specific CPU functionality and not seeing the benefit.

Maybe could even discuss about opting into specific features they want to target.

**Comment by bjorn3** [comment]
This bug will be fixed by https://github.com/llvm/llvm-project/commit/fcca10c69aaab539962d10fcc59a5f074b73b0de once an LLVM version is released that includes it. (Or rather a bit earlier as rustc generally switches to a new LLVM version while it is still a pre-release. This makes it possible to get bugfixes included in the final release I believe.)

**Comment by nnethercote** [comment]
Thanks for the suggestion! Addressed in https://github.com/nnethercote/perf-book/commit/42f42d6315dbdd1991e9bf8363e8bb4b3d79ca48.
