### ISSUE TITLE
Benchmarking: mention that both input and output need to be in a `black_box()`

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#53]
Rust has recently stabilized [`std::hint::black_box`](https://doc.rust-lang.org/stable/std/hint/fn.black_box.html).

It's a common mistake when writing micro-benchmarks to forget to put **both** the inputs and outputs into a `black_box()`. 

More info: https://gendignoux.com/blog/2022/01/31/rust-benchmarks.html

**Comment by nnethercote** [comment]
Thanks for the suggestion, that's an interesting blog post.

The perf book currently doesn't mention `black_box`. The benchmarking chapter is deliberately high level, because getting into detail there could double the length of the book! So I won't add anything here. But I did make a [small change](https://github.com/nnethercote/perf-book/commit/0c21169336b9106b8d0e8d96609b7d2569c4dd8b) to the benchmarking chapter, including changing the link about benchmark tests to [this](https://doc.rust-lang.org/nightly/unstable-book/library-features/test.html). If that page has any shortcomings in its, please feel free to file an issue or PR against it :)



[https://doc.rust-lang.org/nightly/unstable-book/library-features/test.html]

**Comment by Shnatsel** [comment]
I thought it's worth mentioning since it's such a common pitfall.

**Comment by Shnatsel** [comment]
`std::hint::black_box` is now available on stable Rust, too.
