### ISSUE TITLE
mention hashbrown, faster HashMap implementation

### ISSUE THREAD

**Issue by poly000** [nnethercote/perf-book#59]

**Comment by bjorn3** [comment]
libstd uses hashbrown internally. If the hashbrown crate seems faster, that is because it uses a faster hasher by default. Where libstd's default hasher has been chosen for security, hashbrown's one (ahash) has been chosen for better performance. You can use the hasher hashbrown uses by default with libstd too. If you want the best performance you did likely want to use an even faster (but of less quality) hasher. See https://nnethercote.github.io/perf-book/hashing.html
