### ISSUE TITLE
Outdated mention of `tikv-jemallocator`

### ISSUE THREAD

**Issue by Boshen** [nnethercote/perf-book#67]
https://github.com/nnethercote/perf-book/blob/22698c87d13f4aa62e3ce3886a00d4f1d90aec44/src/heap-allocations.md?plain=1#L396-L398

This is no longer the case. They are the same crate now.

https://github.com/tikv/jemallocator#tikv-jemallocator

> The project is published as tikv-jemallocator and jemallocator for historical reasons. The two crates are the same except names. It's OK to use either crate.

**Comment by nnethercote** [comment]
I find this all very confusing. Here's my attempts to understand things.

Repositories
- https://github.com/gnzlbg/jemallocator hasn't been updated since 2019.
- https://github.com/tikv/jemallocator is a fork of https://github.com/gnzlbg/jemallocator that was last updated only a week ago, i.e. has active development.

Crates on crates.io
- https://crates.io/crates/jemallocator exists.
- https://crates.io/crates/tikv-jemallocator also exists.
- Both are on version 0.5.0, and both were last updated on May 25, 2022.
- Both link to https://github.com/tikv/jemallocator.
- I haven't checked their code, but their sizes are 9.39kB and 9.38kB, which are almost identical.

AFAICT, gnzlbg/jemallocator is defunct, tikv/jemallocator is a fork of it that is maintained, and the fork is published to crates.io under two different names. Is that right?

The part of the documentation not quoted in the description above says this:

> But due to lack of permissions, only jemallocator and jemalloc-sys are updated. If you want to use other crates, tikv-xxx versions are still required.

What does that mean? It makes it sounds like it does matter whether you use `jemallocator` or `tikv-jemallocator`.

**Comment by Boshen** [comment]
I quick search leads us to https://github.com/tikv/jemallocator/issues/56

> Currently, the crate we don't have permission to publish is jemallocator-global. So if you need it, then you have to use tikv-jemallocator-global and then all the dependencies will go to tikv-xxx. If you don't need it, choose whichever you like.

**Comment by nnethercote** [comment]
I ended up just removing that paragraph altogether, to avoid getting into the confusing details.
